name: Deploy to VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: [self-hosted]
    steps:
      - name: cleanup and reset permissions to user from docker user
        run: chown -R $USER:$USER $GITHUB_WORKSPACE

      - name: download source code
        uses: actions/checkout@v2

      - name: set environment variables in .env file
        run: |
          echo POSTGRES_USER="${{ secrets.POSTGRES_USER }}" > .env
          echo POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo POSTGRES_DB="${{ secrets.POSTGRES_DB }}" >> .env
          echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
          echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
          echo TESTER_API_KEY="${{ secrets.TESTER_API_KEY }}" >> .env

      - name: build docker images locally
        run: docker-compose -f docker-compose.prod.yml build --parallel

      - name: run docker compose
        run: docker-compose -f docker-compose.prod.yml up -d
